# Generated by Django 4.2.6 on 2023-10-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bottom_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='top_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
