# Generated by Django 4.2.6 on 2023-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottom_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_text',
            field=models.TextField(blank=True),
        ),
    ]
