# Generated by Django 4.2.6 on 2023-10-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_bottom_text_post_top_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='template_id',
        ),
    ]
